import tkinter
import requests
import json
import geopy
import pyowm
import PIL
import time
import threading
import sys
import os
import platform
import webbrowser
import datetime
import socket
import urllib
import re
import traceback
import logging
import random
import math
import subprocess
import getpass
import shutil
import sqlite3
import csv
import smtplib
import imaplib
import pyautogui
import pyperclip
import pytz
import pyqrcode
import pyzbar
import pydub
import pyaudio
import speech_recognition
import gtts
import playsound
import pywhatkit
import pyjokes
import pytube
import pyshorteners
import pyfiglet
